### ISSUE TITLE
How to run your system?

### ISSUE THREAD

**Issue by mlotysz** [VanDavv/Pat2016_Lukasz_Pilatowski#5]
Minimal documentation is needed. I cloned your repo and... 
Readme.md it's not in markdown format. Fix that. You can use https://raw.githubusercontent.com/blstream/AugumentedSzczecin_java/master/README.md as an example.

**Comment by VanDavv** [comment]
Documentation has been written :) and i hope that now it's correctly in markdown format

**Comment by mlotysz** [comment]
Looks good.
