### ISSUE TITLE
Fix representations

### ISSUE THREAD

**Issue by mlotysz** [VanDavv/Pat2016_Lukasz_Pilatowski#6]
Remove copy paste's: Saying, RequestBody (in: ActorResource, MovieResource). Check for details:
http://www.dropwizard.io/0.9.1/docs/manual/core.html#representations

**Comment by VanDavv** [comment]
fixed :) although Saying is not copy paste

**Comment by mlotysz** [comment]
_Saying has to be removed!_ :)

We used to return entity representation not string and your sample implementation:

```
    public Saying postActor(Actor actor) {
        dao.create(actor);
        return new Saying("Added : " + actor.toString());
    }
```

becomes then clean and simple, yet easy to consume for your future REST clients:

```
    public Actor postActor(@Valid final Actor actor) {
        return dao.create(actor); // TODO for you: make sure dao.create returns created entity!
    }
```

Fix rest of your resources implementation according to this simple rules:
- POST/PUT return created/updated entity
- GET - you should know: entity list for all and entity when id is present in URL
- DELETE - could be void

**Comment by VanDavv** [comment]
Ok, Saying.java has been removed :)

**Comment by mlotysz** [comment]
Looks better. BUT
- DELETE should return nothing `void`
- your last commit doesn't change tests at all - it means those test are not testing your rest api thoroughly - fix them to check entity which is returned
- learn and use @Valid annotation on resource parameters - add some test to cover negative scenarios, for e.g. some client send you new Actor without required parameter or update for non existent entity - those cases you should cover in test!
  And I think it will be enough to close this issue.

As an extra fixes you can make your model classes immutable - use `final` keyword whenever you can.

**Comment by VanDavv** [comment]
Haha just when You were writing this message i've pushed another commit with changed tests :D I didn't expect such a quick answer

**Comment by mlotysz** [comment]
Those new *Services which are doing... nothing could be probably removed.

**Comment by VanDavv** [comment]
Ok, they're removed, i fouhgt it could be usefull someday.

**Comment by mlotysz** [comment]
Seems you don't know what YAGNI means. Check it out, people are discussing it a lot: https://javax0.wordpress.com/2015/08/12/some-thoughts-about-yagni/

**Comment by mlotysz** [comment]
Add some negative scenarios to finish this issue and task 1! :)

**Comment by VanDavv** [comment]
Ok, commit pushed :)

**Comment by mlotysz** [comment]
Gratuluję.
